"""LanceDB-backed per-folder index store.

Each indexed folder grows a `.hydra-index/` directory:

    .hydra-index/
      meta.yaml          # embedder ids + dimensions + chunking version + timestamps
      files.json         # rel_path -> {mtime, size, chunk_ids}; drives incremental refresh
      code.lance/        # LanceDB table for code chunks (one row per chunk)
      prose.lance/       # LanceDB table for prose chunks

The schema is intentionally permissive so future hydra versions can add
columns without rebuilding existing indexes -- LanceDB's columnar format
supports that. We only require the columns hydra reads back.
"""
from __future__ import annotations

import json
import time
import uuid
from pathlib import Path
from typing import Iterable

import yaml

# LanceDB import is deferred so non-RAG hydra commands don't pay the cost.

INDEX_DIR_NAME = ".hydra-index"
META_FILENAME = "meta.yaml"
FILES_FILENAME = "files.json"
CODE_TABLE = "code"
PROSE_TABLE = "prose"

# Bumped when chunking changes in a way that invalidates existing chunks.
CHUNKING_VERSION = 1


def index_dir(root: Path) -> Path:
    return Path(root).expanduser().resolve() / INDEX_DIR_NAME


def has_index(root: Path) -> bool:
    return (index_dir(root) / META_FILENAME).is_file()


def read_meta(root: Path) -> dict:
    p = index_dir(root) / META_FILENAME
    if not p.is_file():
        return {}
    with open(p) as f:
        return yaml.safe_load(f) or {}


def write_meta(root: Path, meta: dict) -> Path:
    d = index_dir(root)
    d.mkdir(parents=True, exist_ok=True)
    p = d / META_FILENAME
    with open(p, "w") as f:
        f.write("# hydra-llm index metadata. Regenerated by `hydra-llm index`.\n")
        f.write("# Contains the embedder ids and chunking version this index was built with.\n\n")
        yaml.safe_dump(meta, f, sort_keys=False, default_flow_style=False)
    return p


def read_files_registry(root: Path) -> dict:
    p = index_dir(root) / FILES_FILENAME
    if not p.is_file():
        return {}
    try:
        with open(p) as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}


def write_files_registry(root: Path, registry: dict) -> Path:
    d = index_dir(root)
    d.mkdir(parents=True, exist_ok=True)
    p = d / FILES_FILENAME
    with open(p, "w") as f:
        json.dump(registry, f, indent=2, sort_keys=True)
    return p


def chunk_id() -> str:
    return uuid.uuid4().hex


def _connect(root: Path):
    """Open the LanceDB connection at root/.hydra-index/."""
    import lancedb
    d = index_dir(root)
    d.mkdir(parents=True, exist_ok=True)
    return lancedb.connect(str(d))


def _ensure_table(db, name: str, dimensions: int):
    """Open or create a chunk table with the canonical schema."""
    import pyarrow as pa  # via lancedb dep

    if name in db.table_names():
        return db.open_table(name)
    schema = pa.schema([
        pa.field("chunk_id", pa.string()),
        pa.field("rel_path", pa.string()),
        pa.field("byte_start", pa.int64()),
        pa.field("byte_end", pa.int64()),
        pa.field("line_start", pa.int32()),
        pa.field("line_end", pa.int32()),
        pa.field("mtime", pa.float64()),
        pa.field("text", pa.string()),
        pa.field("vector", pa.list_(pa.float32(), dimensions)),
    ])
    return db.create_table(name, schema=schema)


def upsert_chunks(root: Path, kind: str, dimensions: int, rows: list[dict]) -> None:
    """Insert chunk rows into the code/prose table. Rows are dicts matching
    the schema; vector must already be length=dimensions float32.
    """
    if not rows:
        return
    db = _connect(root)
    table_name = CODE_TABLE if kind == "code" else PROSE_TABLE
    tbl = _ensure_table(db, table_name, dimensions)
    tbl.add(rows)


def delete_by_chunk_ids(root: Path, kind: str, chunk_ids: list[str]) -> int:
    """Delete a set of chunk_ids from the code/prose table. Returns count
    requested (LanceDB's delete doesn't tell us how many actually matched).
    """
    if not chunk_ids:
        return 0
    db = _connect(root)
    table_name = CODE_TABLE if kind == "code" else PROSE_TABLE
    if table_name not in db.table_names():
        return 0
    tbl = db.open_table(table_name)
    # Build a SQL IN-clause; chunk_ids are hex uuids so quoting is trivial.
    ids_quoted = ", ".join(f"'{cid}'" for cid in chunk_ids)
    tbl.delete(f"chunk_id IN ({ids_quoted})")
    return len(chunk_ids)


def search(root: Path, kind: str, query_vector, top_k: int = 10) -> list[dict]:
    """K-NN search against the named table. Returns a list of result dicts
    with score, rel_path, byte_start/end, line_start/end, text, chunk_id.
    """
    db = _connect(root)
    table_name = CODE_TABLE if kind == "code" else PROSE_TABLE
    if table_name not in db.table_names():
        return []
    tbl = db.open_table(table_name)
    # LanceDB returns a Lance Table; .to_list() yields dicts.
    df = tbl.search(query_vector).limit(top_k).to_list()
    out = []
    for row in df:
        out.append({
            "chunk_id": row.get("chunk_id"),
            "rel_path": row.get("rel_path"),
            "byte_start": row.get("byte_start"),
            "byte_end": row.get("byte_end"),
            "line_start": row.get("line_start"),
            "line_end": row.get("line_end"),
            "text": row.get("text"),
            # LanceDB names the distance column _distance for vector search.
            "distance": row.get("_distance"),
        })
    return out


def chunk_count(root: Path, kind: str) -> int:
    """Quick row count for a table. 0 if the table doesn't exist yet."""
    try:
        db = _connect(root)
    except Exception:
        return 0
    table_name = CODE_TABLE if kind == "code" else PROSE_TABLE
    if table_name not in db.table_names():
        return 0
    tbl = db.open_table(table_name)
    return tbl.count_rows()


def now_iso() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


# --- registry of indexed folders ----------------------------------------------
#
# A small JSON file at $XDG_STATE_HOME/hydra-llm/rag-stores.json that lists
# every folder hydra has indexed. Used by `hydra-llm rag stores`.

def _registry_path():
    from . import paths
    return paths.RAG_STORES_REGISTRY


def load_registry() -> dict:
    p = _registry_path()
    if not p.is_file():
        return {"stores": []}
    try:
        with open(p) as f:
            return json.load(f) or {"stores": []}
    except (OSError, json.JSONDecodeError):
        return {"stores": []}


def save_registry(reg: dict) -> Path:
    p = _registry_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "w") as f:
        json.dump(reg, f, indent=2, sort_keys=True)
    return p


def register_store(root: Path) -> None:
    """Add `root` to the global stores registry (idempotent, by absolute path)."""
    rp = str(Path(root).expanduser().resolve())
    reg = load_registry()
    stores = reg.get("stores") or []
    for s in stores:
        if s.get("path") == rp:
            s["last_indexed"] = now_iso()
            save_registry(reg)
            return
    stores.append({"path": rp, "first_indexed": now_iso(), "last_indexed": now_iso()})
    reg["stores"] = stores
    save_registry(reg)


def unregister_store(root: Path) -> bool:
    rp = str(Path(root).expanduser().resolve())
    reg = load_registry()
    before = len(reg.get("stores") or [])
    reg["stores"] = [s for s in (reg.get("stores") or []) if s.get("path") != rp]
    save_registry(reg)
    return len(reg["stores"]) < before


def prune_registry() -> list[str]:
    """Drop registry entries whose folder or .hydra-index/ no longer exists.
    Returns list of paths that were removed.
    """
    reg = load_registry()
    keep = []
    dropped = []
    for s in reg.get("stores") or []:
        rp = Path(s.get("path", ""))
        if rp.is_dir() and (rp / INDEX_DIR_NAME).is_dir():
            keep.append(s)
        else:
            dropped.append(str(rp))
    reg["stores"] = keep
    save_registry(reg)
    return dropped
