#!/usr/bin/env bash
# Dev install: symlinks from the working tree into ~/.local so edits to source
# are picked up immediately. No sudo, no copying. Mirrors the FHS layout used
# by the system install, just rooted at ~/.local/share/hydra-llm.
#
# Called from the Makefile's dev-install target.
set -euo pipefail

USER_BIN="${1:?missing user bin dir}"
USER_LIB="${2:?missing user lib dir}"
USER_SHARE="${3:?missing user share dir}"

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

mkdir -p "$USER_BIN" "$USER_LIB" "$USER_SHARE/presets" "$USER_SHARE/personas"

ln -sfn "$HERE/lib/hydra_llm"             "$USER_LIB/hydra_llm"
ln -sfn "$HERE/catalog/catalog.yaml"      "$USER_SHARE/catalog.yaml"
ln -sfn "$HERE/personas/friendly-tutor.md" "$USER_SHARE/personas/friendly-tutor.md"
ln -sfn "$HERE/personas/concise-coder.md"  "$USER_SHARE/personas/concise-coder.md"

# Write a tiny launcher that points at the source tree, no env vars required
# at call time.
cat > "$USER_BIN/hydra-llm" <<EOF
#!/usr/bin/env bash
# Dev launcher generated by 'make dev-install'. Re-run dev-install to refresh.
export HYDRA_LLM_LIB="$HERE/lib"
export HYDRA_LLM_CATALOG="$USER_SHARE/catalog.yaml"
exec "$HERE/bin/hydra-llm" "\$@"
EOF
chmod 0755 "$USER_BIN/hydra-llm"

cat <<EOF
Installed:
  $USER_BIN/hydra-llm         (launcher, points at $HERE)
  $USER_LIB/hydra_llm         (symlink to lib/hydra_llm)
  $USER_SHARE/catalog.yaml    (symlink to shipped catalog)
  $USER_SHARE/personas/       (symlinks to shipped personas)

Make sure $USER_BIN is on your PATH. Test:
  hydra-llm doctor
  hydra-llm list-online
EOF
