#!/usr/bin/env bash
# End-user install. Copies files (no symlinks) so the source tree can be
# deleted after install. Mirrors the FHS layout the .deb uses, just rooted
# at $HOME/.local. No sudo needed.
set -euo pipefail

USER_BIN="${1:?missing user bin dir}"
USER_LIB="${2:?missing user lib dir}"
USER_SHARE="${3:?missing user share dir}"

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

mkdir -p "$USER_BIN" "$USER_LIB/hydra_llm" "$USER_SHARE/personas" "$USER_SHARE/presets" "$USER_SHARE/docker" "$USER_SHARE/scripts"

# Copy library
install -m 0644 "$HERE"/lib/hydra_llm/*.py "$USER_LIB/hydra_llm/"

# Copy shared assets
install -m 0644 "$HERE"/catalog/catalog.yaml      "$USER_SHARE/catalog.yaml"
install -m 0644 "$HERE"/personas/friendly-tutor.md "$USER_SHARE/personas/friendly-tutor.md"
install -m 0644 "$HERE"/personas/concise-coder.md  "$USER_SHARE/personas/concise-coder.md"
install -m 0644 "$HERE"/docker/Dockerfile.vulkan   "$USER_SHARE/docker/Dockerfile.vulkan"
install -m 0644 "$HERE"/docker/Dockerfile.cpu      "$USER_SHARE/docker/Dockerfile.cpu"

# Ship the uninstall scripts so `hydra-llm uninstall|wipe` can find them.
install -m 0755 "$HERE"/scripts/user-uninstall.sh  "$USER_SHARE/scripts/user-uninstall.sh"

# Write the launcher. Points at the user-install copies.
cat > "$USER_BIN/hydra-llm" <<EOF
#!/usr/bin/env bash
# hydra-llm user launcher. Generated by user-install.
export HYDRA_LLM_LIB="$USER_LIB"
export HYDRA_LLM_CATALOG="$USER_SHARE/catalog.yaml"
export HYDRA_LLM_DOCKER_DIR="$USER_SHARE/docker"
export HYDRA_LLM_SHARE="$USER_SHARE"
exec python3 -B -c "import sys; sys.path.insert(0, '$USER_LIB'); from hydra_llm.cli import main; main()" "\$@"
EOF
chmod 0755 "$USER_BIN/hydra-llm"

# Short alias for easier typing. Both names live in the same dir, so a relative
# symlink is fine and survives renaming $USER_BIN.
ln -sf hydra-llm "$USER_BIN/hydrallm"

# DE-aware Plasmoid install. If Plasma 6 is the running desktop, copy the
# widget package into ~/.local/share/plasma/plasmoids/ so it shows up in the
# panel's "Add Widgets..." dialog. No sudo. Skipped when not on Plasma.
PLASMOID_ID="com.github.ra-yavuz.hydra-llm"
PLASMOID_USER_DIR="$HOME/.local/share/plasma/plasmoids/$PLASMOID_ID"
case "${XDG_CURRENT_DESKTOP:-}${DESKTOP_SESSION:-}" in
    *KDE*|*kde*|*plasma*|*Plasma*)
        echo "Detected KDE Plasma desktop, installing the panel widget too."
        mkdir -p "$PLASMOID_USER_DIR"
        rm -rf "$PLASMOID_USER_DIR"/contents
        install -m 0644 "$HERE/plasmoid/metadata.json" "$PLASMOID_USER_DIR/metadata.json"
        cp -r "$HERE/plasmoid/contents" "$PLASMOID_USER_DIR/contents"
        ;;
    *)
        ;;
esac

cat <<EOF
Installed to $USER_BIN/hydra-llm.
Library:   $USER_LIB/hydra_llm
Assets:    $USER_SHARE
EOF
